name: Check Requirements

on:
  push:
    paths:
      - "requirements.txt"

  pull_request:
    paths:
      - "requirements.txt"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            TARGET: Linux
          - os: macos-latest
            TARGET: macOS
          - os: windows-latest
            TARGET: Windows
        python-version: [ "3.10" ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: pip install -r requirements.txt
      
    - name: Install gpu dependencies
      if: matrix.TARGET != 'macOS'
      run: pip3 install torch==2.0.1+cu117 torchvision==0.15.2+cu117 torchaudio==2.0.2+cu117 --index-url https://download.pytorch.org/whl/cu117
