name: PyLint

#on: [push, pull_request]
on:
  push:
    branches:
      - CI
    paths:
      #- "requirements.txt"

  pull_request:
    branches:
      - CI
    paths:
      #- "requirements.txt"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Python Linter
      uses: rakuri255/UltraSinger@CI