name: PyLint

on: [push, pull_request]

jobs:
  python-lint:
    runs-on: ubuntu-latest
    name: CI workflow
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: linting
      uses: rakuri255/UltraSinger@main